CREATE TABLE refresh_tokens(

id UUID PRIMARY KEY,
user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
token varchar(255) NOT NULL UNIQUE,

created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
expires_at TIMESTAMP NOT NULL,
revoked_at TIMESTAMP DEFAULT NULL

)