CREATE TABLE users(
id UUID PRIMARY KEY,
name VARCHAR (80) NOT NULL ,
password varchar(255) NOT NULL,
cpf varchar(11) NOT NULL UNIQUE,
email varchar(100) NOT NULL UNIQUE,


cep VARCHAR(8) NOT NULL,
street VARCHAR(120) NOT NULL,
number VARCHAR(10) NOT NULL,
complement VARCHAR(60),
neighborhood VARCHAR(80) NOT NULL,
city VARCHAR(80) NOT NULL,
state VARCHAR(30) NOT NULL CHECK (state IN (
        'ACRE', 'ALAGOAS', 'AMAPA', 'AMAZONAS', 'BAHIA', 'CEARA', 'DISTRITO_FEDERAL',
        'ESPIRITO_SANTO', 'GOIAS', 'MARANHAO', 'MATO_GROSSO', 'MATO_GROSSO_DO_SUL',
        'MINAS_GERAIS', 'PARA', 'PARAIBA', 'PARANA', 'PERNAMBUCO', 'PIAUI',
        'RIO_DE_JANEIRO', 'RIO_GRANDE_DO_NORTE', 'RIO_GRANDE_DO_SUL', 'RONDONIA',
        'RORAIMA', 'SANTA_CATARINA', 'SAO_PAULO', 'SERGIPE', 'TOCANTINS'
    )),


created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);