CREATE TABLE venues (
id UUID PRIMARY KEY,
name varchar(155) NOT NULL,
total_capacity INT NOT NULL,

cep VARCHAR(8) NOT NULL,
street VARCHAR(120) NOT NULL,
number VARCHAR(10) NOT NULL,
complement VARCHAR(60),
neighborhood VARCHAR(80) NOT NULL,
city VARCHAR(80) NOT NULL,
 state VARCHAR(30) NOT NULL CHECK (state IN (
        'ACRE', 'ALAGOAS', 'AMAPA', 'AMAZONAS', 'BAHIA', 'CEARA', 'DISTRITO_FEDERAL',
        'ESPIRITO_SANTO', 'GOIAS', 'MARANHAO', 'MATO_GROSSO', 'MATO_GROSSO_DO_SUL',
        'MINAS_GERAIS', 'PARA', 'PARAIBA', 'PARANA', 'PERNAMBUCO', 'PIAUI',
        'RIO_DE_JANEIRO', 'RIO_GRANDE_DO_NORTE', 'RIO_GRANDE_DO_SUL', 'RONDONIA',
        'RORAIMA', 'SANTA_CATARINA', 'SAO_PAULO', 'SERGIPE', 'TOCANTINS'
    ))

);
