CREATE TABLE event_sessions(

id UUID PRIMARY KEY,
event_id UUID NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
venue_id UUID NOT NULL REFERENCES venues(id) ON DELETE RESTRICT,
session_status varchar(20) NOT NULL CHECK(session_status in ('ANNOUNCED','OPEN','SOLD_OUT','CLOSED','CANCELLED')) DEFAULT 'ANNOUNCED',
starts_at TIMESTAMP NOT NULL ,

created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP


)