CREATE TABLE orders (

id UUID PRIMARY KEY,
user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
total_value NUMERIC(10,2) NOT NULL CHECK(total_value >= 0),
order_status varchar(20) NOT NULL CHECK (order_status in ('PENDING','PAID','CANCELLED','EXPIRED','REFUNDED')),

created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
expiration_at TIMESTAMP NOT NULL


);